use std::env;
use std::ffi::{OsStr, OsString};
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

pub const GAP_SYS_ROOT: &str = "GAP_SYS_ROOT";
pub const GAP_SYS_GAP_BIN: &str = "GAP_SYS_GAP_BIN";
pub const GAP_SYS_INCLUDE_DIRS: &str = "GAP_SYS_INCLUDE_DIRS";
pub const GAP_SYS_LIB_DIRS: &str = "GAP_SYS_LIB_DIRS";
const GAP_ROOT_QUERY: &str = "for p in GAPInfo.RootPaths do if IsExistingFile(Concatenation(p,\"lib/init.g\")) then Print(p,\"\\n\"); fi; od; QUIT;";

#[derive(Clone, Debug, PartialEq, Eq)]
pub enum HeaderLayout {
    IncludeSubdir,
    Direct,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GapConfig {
    pub root: PathBuf,
    pub include_dirs: Vec<PathBuf>,
    pub lib_dirs: Vec<PathBuf>,
    pub header_layout: HeaderLayout,
}

#[derive(Clone, Debug, Default)]
pub struct DiscoveryEnv {
    pub root: Option<OsString>,
    pub gap_bin: Option<OsString>,
    pub include_dirs: Option<OsString>,
    pub lib_dirs: Option<OsString>,
}

impl DiscoveryEnv {
    pub fn from_process_env() -> Self {
        Self {
            root: env::var_os(GAP_SYS_ROOT),
            gap_bin: env::var_os(GAP_SYS_GAP_BIN),
            include_dirs: env::var_os(GAP_SYS_INCLUDE_DIRS),
            lib_dirs: env::var_os(GAP_SYS_LIB_DIRS),
        }
    }
}

pub fn discover_gap_config(env: &DiscoveryEnv) -> Result<GapConfig, String> {
    let root = env
        .root
        .as_deref()
        .and_then(nonempty_path)
        .map(Ok)
        .unwrap_or_else(|| query_gap_root(env))?;
    let root = resolve_gap_root(&root)?;

    let include_dirs = match env.include_dirs.as_deref() {
        Some(paths) => parse_path_list(paths),
        None => infer_include_dirs(&root),
    };
    let header_layout = find_header_layout(&include_dirs).ok_or_else(|| {
        format!(
            "Could not find GAP headers. Tried include directories: {}. \
             Set {GAP_SYS_INCLUDE_DIRS} or {GAP_SYS_ROOT}.",
            display_paths(&include_dirs)
        )
    })?;

    let lib_dirs = match env.lib_dirs.as_deref() {
        Some(paths) => parse_path_list(paths),
        None => infer_lib_dirs(&root),
    };
    if !lib_dirs.iter().any(|dir| contains_libgap(dir)) {
        return Err(format!(
            "Could not find libgap. Tried library directories: {}. \
             Set {GAP_SYS_LIB_DIRS} or {GAP_SYS_ROOT}.",
            display_paths(&lib_dirs)
        ));
    }

    Ok(GapConfig {
        root,
        include_dirs,
        lib_dirs,
        header_layout,
    })
}

pub fn wrapper_header(layout: &HeaderLayout) -> String {
    let includes = match layout {
        HeaderLayout::IncludeSubdir => "#include <gap/libgap-api.h>\n#include <gap/gap_all.h>",
        HeaderLayout::Direct => "#include \"libgap-api.h\"\n#include \"gap_all.h\"",
    };

    format!(
        "\
// Generated by gap-sys build.rs.
// We must define EXPORT_INLINE as static inline for bindgen to work with libgap.
#define EXPORT_INLINE static inline

// Include all of GAP's headers.
{includes}

// Wrapper around macros.
static inline int SYSGAP_Enter() {{
    return GAP_Enter();
}}

static inline void SYSGAP_Leave() {{
    GAP_Leave();
}}

#if defined(GAP_KERNEL_API_VERSION) && GAP_KERNEL_API_VERSION >= 10000
static TypOutputFile SYSGAP_OUTPUT_STREAM = {{ 0 }};
#endif

static inline UInt SYSGAP_OpenOutputStream(Obj stream) {{
#if defined(GAP_KERNEL_API_VERSION) && GAP_KERNEL_API_VERSION >= 10000
    return OpenOutputStream(&SYSGAP_OUTPUT_STREAM, stream);
#else
    return OpenOutputStream(stream);
#endif
}}

static inline UInt SYSGAP_CloseOutput(void) {{
#if defined(GAP_KERNEL_API_VERSION) && GAP_KERNEL_API_VERSION >= 10000
    return CloseOutput(&SYSGAP_OUTPUT_STREAM);
#else
    return CloseOutput();
#endif
}}

static inline Obj SYSGAP_CallFunc2Args(Obj func, Obj a1, Obj a2) {{
    Obj args[2] = {{ a1, a2 }};
    return GAP_CallFuncArray(func, 2, args);
}}

static inline void SYSGAP_MarkBag(Obj obj) {{
#if defined(GAP_KERNEL_API_VERSION) && GAP_KERNEL_API_VERSION >= 10000
    GAP_MarkBag(obj);
#else
    MarkBag(obj);
#endif
}}
"
    )
}

fn query_gap_root(env: &DiscoveryEnv) -> Result<PathBuf, String> {
    let explicit_gap_bin = env.gap_bin.as_ref().is_some();
    let gap_bin = env
        .gap_bin
        .as_deref()
        .filter(|bin| !bin.is_empty())
        .map(PathBuf::from)
        .unwrap_or_else(|| PathBuf::from("gap"));

    match run_gap_command(&gap_bin, ["--print-gaproot"]) {
        Ok(output) if output.status.success() => {
            if let Some(root) = parse_gap_root_stdout(&output.stdout) {
                return Ok(root);
            }
        }
        Ok(_) => {}
        Err(err) if explicit_gap_bin => {
            return Err(format!(
                "Could not run `{}`: {err}. Set {GAP_SYS_ROOT}.",
                gap_bin.display()
            ));
        }
        Err(_) => {
            return Err(format!(
                "Could not run `gap --print-gaproot`. Set {GAP_SYS_ROOT} or {GAP_SYS_GAP_BIN}."
            ));
        }
    }

    match run_gap_command(&gap_bin, ["-q", "-c", GAP_ROOT_QUERY]) {
        Ok(output) if output.status.success() => {
            parse_gap_root_stdout(&output.stdout).ok_or_else(|| {
                format!(
                    "`{} -q -c <gap-root-query>` did not print a usable GAP root. Set {GAP_SYS_ROOT}.",
                    gap_bin.display()
                )
            })
        }
        Ok(output) if explicit_gap_bin => Err(format!(
            "`{} -q -c <gap-root-query>` failed with status {}. Set {GAP_SYS_ROOT}.",
            gap_bin.display(),
            output.status
        )),
        Ok(_) => Err(format!(
            "Could not discover GAP root with `gap --print-gaproot` or a GAPInfo.RootPaths query. Set {GAP_SYS_ROOT}."
        )),
        Err(err) if explicit_gap_bin => Err(format!(
            "Could not run `{}`: {err}. Set {GAP_SYS_ROOT}.",
            gap_bin.display()
        )),
        Err(_) => Err(format!(
            "Could not run GAP root discovery commands. Set {GAP_SYS_ROOT} or {GAP_SYS_GAP_BIN}."
        )),
    }
}

fn run_gap_command<const N: usize>(
    gap_bin: &Path,
    args: [&str; N],
) -> std::io::Result<std::process::Output> {
    Command::new(gap_bin)
        .args(args)
        .stdin(Stdio::null())
        .output()
}

fn parse_gap_root_stdout(stdout: &[u8]) -> Option<PathBuf> {
    let stdout = String::from_utf8_lossy(stdout);
    let mut existing_dir = None;

    for line in stdout.lines() {
        let Some(path) = parse_gap_root_line(line) else {
            continue;
        };

        if path.join("lib").join("init.g").is_file() {
            return Some(path);
        }

        if existing_dir.is_none() && path.is_dir() {
            existing_dir = Some(path);
        }
    }

    existing_dir
}

fn parse_gap_root_line(line: &str) -> Option<PathBuf> {
    let line = line.trim();
    let line = line.strip_prefix("gap>").unwrap_or(line).trim();

    if line.is_empty() || !is_plausible_path(line) {
        return None;
    }

    Some(PathBuf::from(line))
}

fn is_plausible_path(path: &str) -> bool {
    path.starts_with('/')
        || path.starts_with('\\')
        || path.starts_with("./")
        || path.starts_with("../")
        || path
            .as_bytes()
            .get(1)
            .map(|byte| *byte == b':')
            .unwrap_or(false)
}

fn resolve_gap_root(root: &Path) -> Result<PathBuf, String> {
    let candidates = gap_root_candidates(root);
    for candidate in &candidates {
        if candidate.join("lib").join("init.g").is_file() {
            return Ok(candidate.clone());
        }
    }

    Err(format!(
        "GAP root `{}` does not contain `lib/init.g`. Tried: {}. Set {GAP_SYS_ROOT} to a valid GAP root.",
        root.display(),
        display_paths(&candidates)
    ))
}

fn gap_root_candidates(root: &Path) -> Vec<PathBuf> {
    let mut candidates = Vec::new();
    push_unique(&mut candidates, root.to_path_buf());

    for base in root.ancestors().take(4) {
        push_unique(&mut candidates, base.join("libexec"));
        push_unique(&mut candidates, base.join("share").join("gap"));
        push_unique(&mut candidates, base.join("lib").join("gap"));
    }

    candidates
}

fn infer_include_dirs(root: &Path) -> Vec<PathBuf> {
    let mut dirs = Vec::new();

    let source_dir = root.join("src");
    if source_dir.join("libgap-api.h").is_file() && source_dir.join("gap_all.h").is_file() {
        push_unique(&mut dirs, source_dir);
        let build_dir = root.join("build");
        if build_dir.is_dir() {
            push_unique(&mut dirs, build_dir);
        }
    }

    push_include_candidate(&mut dirs, root.join("include"));

    if let Some(parent) = root.parent() {
        push_include_candidate(&mut dirs, parent.join("include"));

        if let Some(prefix) = parent.parent() {
            push_include_candidate(&mut dirs, prefix.join("include"));
        }
    }

    dirs
}

fn push_include_candidate(dirs: &mut Vec<PathBuf>, dir: PathBuf) {
    if dir.join("gap").join("libgap-api.h").is_file() && dir.join("gap").join("gap_all.h").is_file()
    {
        push_unique(dirs, dir);
    }
}

fn infer_lib_dirs(root: &Path) -> Vec<PathBuf> {
    let mut dirs = Vec::new();

    push_lib_candidate(&mut dirs, root.to_path_buf());
    push_lib_candidates_under(&mut dirs, root.join("lib"));

    if let Some(parent) = root.parent() {
        push_lib_candidate(&mut dirs, parent.to_path_buf());
        push_lib_candidates_under(&mut dirs, parent.join("lib"));

        if let Some(prefix) = parent.parent().filter(|prefix| prefix.parent().is_some()) {
            push_lib_candidates_under(&mut dirs, prefix.join("lib"));
            push_lib_candidates_under(&mut dirs, prefix.join("lib64"));
        }
    }

    dirs
}

fn push_lib_candidates_under(dirs: &mut Vec<PathBuf>, dir: PathBuf) {
    push_lib_candidate(dirs, dir.clone());

    let Ok(entries) = dir.read_dir() else {
        return;
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            push_lib_candidate(dirs, path);
        }
    }
}

fn push_lib_candidate(dirs: &mut Vec<PathBuf>, dir: PathBuf) {
    if contains_libgap(&dir) {
        push_unique(dirs, dir);
    }
}

fn find_header_layout(include_dirs: &[PathBuf]) -> Option<HeaderLayout> {
    for dir in include_dirs {
        if dir.join("gap").join("libgap-api.h").is_file()
            && dir.join("gap").join("gap_all.h").is_file()
        {
            return Some(HeaderLayout::IncludeSubdir);
        }
    }

    for dir in include_dirs {
        if dir.join("libgap-api.h").is_file() && dir.join("gap_all.h").is_file() {
            return Some(HeaderLayout::Direct);
        }
    }

    None
}

fn contains_libgap(dir: &Path) -> bool {
    let Ok(entries) = dir.read_dir() else {
        return false;
    };

    entries.flatten().any(|entry| {
        entry
            .file_name()
            .to_str()
            .map(is_libgap_file_name)
            .unwrap_or(false)
    })
}

fn is_libgap_file_name(name: &str) -> bool {
    matches!(
        name,
        "libgap.so" | "libgap.dylib" | "libgap.a" | "libgap.dll" | "libgap.dll.a" | "gap.dll"
    ) || name.starts_with("libgap.so.")
        || (name.starts_with("libgap.") && name.ends_with(".dylib"))
}

fn parse_path_list(paths: &OsStr) -> Vec<PathBuf> {
    env::split_paths(paths)
        .filter(|path| !path.as_os_str().is_empty())
        .collect()
}

fn nonempty_path(path: &OsStr) -> Option<PathBuf> {
    if path.is_empty() {
        None
    } else {
        Some(PathBuf::from(path))
    }
}

fn push_unique(paths: &mut Vec<PathBuf>, path: PathBuf) {
    if !paths.iter().any(|existing| existing == &path) {
        paths.push(path);
    }
}

fn display_paths(paths: &[PathBuf]) -> String {
    if paths.is_empty() {
        "<none>".to_string()
    } else {
        paths
            .iter()
            .map(|path| path.display().to_string())
            .collect::<Vec<_>>()
            .join(", ")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::time::{SystemTime, UNIX_EPOCH};

    #[test]
    fn discovers_source_style_gap_root() {
        let root = temp_root("source-style");
        write_file(root.join("lib/init.g"));
        write_file(root.join("src/libgap-api.h"));
        write_file(root.join("src/gap_all.h"));
        write_file(root.join("build/config.h"));
        write_file(root.join("libgap.dylib"));

        let config = discover_gap_config(&DiscoveryEnv {
            root: Some(root.clone().into_os_string()),
            ..DiscoveryEnv::default()
        })
        .unwrap();

        assert_eq!(config.root, root);
        assert_eq!(config.header_layout, HeaderLayout::Direct);
        assert!(config.include_dirs.contains(&config.root.join("src")));
        assert!(config.include_dirs.contains(&config.root.join("build")));
        assert_eq!(config.lib_dirs, vec![config.root.clone()]);
    }

    #[test]
    fn discovers_installed_style_gap_root() {
        let base = temp_root("installed-style");
        let root = base.join("lib/gap");
        write_file(root.join("lib/init.g"));
        write_file(base.join("include/gap/libgap-api.h"));
        write_file(base.join("include/gap/gap_all.h"));
        write_file(base.join("lib/libgap.so"));

        let config = discover_gap_config(&DiscoveryEnv {
            root: Some(root.clone().into_os_string()),
            ..DiscoveryEnv::default()
        })
        .unwrap();

        assert_eq!(config.root, root);
        assert_eq!(config.header_layout, HeaderLayout::IncludeSubdir);
        assert_eq!(config.include_dirs, vec![base.join("include")]);
        assert_eq!(config.lib_dirs, vec![base.join("lib")]);
    }

    #[test]
    fn explicit_env_vars_override_inferred_paths() {
        let base = temp_root("explicit-env");
        let root = base.join("gaproot");
        let include = base.join("custom-include");
        let lib = base.join("custom-lib");
        write_file(root.join("lib/init.g"));
        write_file(root.join("src/libgap-api.h"));
        write_file(root.join("src/gap_all.h"));
        write_file(root.join("libgap.dylib"));
        write_file(include.join("gap/libgap-api.h"));
        write_file(include.join("gap/gap_all.h"));
        write_file(lib.join("libgap.so"));

        let include_paths = env::join_paths([include.clone()]).unwrap();
        let lib_paths = env::join_paths([lib.clone()]).unwrap();
        let config = discover_gap_config(&DiscoveryEnv {
            root: Some(root.into_os_string()),
            include_dirs: Some(include_paths),
            lib_dirs: Some(lib_paths),
            ..DiscoveryEnv::default()
        })
        .unwrap();

        assert_eq!(config.header_layout, HeaderLayout::IncludeSubdir);
        assert_eq!(config.include_dirs, vec![include]);
        assert_eq!(config.lib_dirs, vec![lib]);
    }

    #[test]
    fn reports_missing_headers() {
        let root = temp_root("missing-headers");
        write_file(root.join("lib/init.g"));
        write_file(root.join("libgap.dylib"));

        let err = discover_gap_config(&DiscoveryEnv {
            root: Some(root.into_os_string()),
            ..DiscoveryEnv::default()
        })
        .unwrap_err();

        assert!(err.contains("Could not find GAP headers"));
    }

    #[test]
    fn reports_missing_libgap() {
        let root = temp_root("missing-libgap");
        write_file(root.join("lib/init.g"));
        write_file(root.join("src/libgap-api.h"));
        write_file(root.join("src/gap_all.h"));

        let err = discover_gap_config(&DiscoveryEnv {
            root: Some(root.into_os_string()),
            ..DiscoveryEnv::default()
        })
        .unwrap_err();

        assert!(err.contains("Could not find libgap"));
    }

    #[test]
    fn discovers_multiarch_lib_dir() {
        let base = temp_root("multiarch-lib");
        let root = base.join("share/gap");
        let include = base.join("include");
        let lib = base.join("lib/x86_64-linux-gnu");
        write_file(root.join("lib/init.g"));
        write_file(include.join("gap/libgap-api.h"));
        write_file(include.join("gap/gap_all.h"));
        write_file(lib.join("libgap.so"));

        let config = discover_gap_config(&DiscoveryEnv {
            root: Some(root.into_os_string()),
            ..DiscoveryEnv::default()
        })
        .unwrap();

        assert_eq!(config.include_dirs, vec![include]);
        assert_eq!(config.lib_dirs, vec![lib]);
    }

    #[test]
    fn resolves_homebrew_package_root_to_libexec_root() {
        let cellar = temp_root("homebrew-libexec");
        let printed_root = cellar.join("lib/gap");
        let actual_root = cellar.join("libexec");
        write_file(printed_root.join("pkg/README"));
        write_file(actual_root.join("lib/init.g"));
        write_file(actual_root.join("src/libgap-api.h"));
        write_file(actual_root.join("src/gap_all.h"));
        write_file(actual_root.join("build/config.h"));
        write_file(actual_root.join("libgap.dylib"));

        let config = discover_gap_config(&DiscoveryEnv {
            root: Some(printed_root.into_os_string()),
            ..DiscoveryEnv::default()
        })
        .unwrap();

        assert_eq!(config.root, actual_root);
        assert_eq!(config.header_layout, HeaderLayout::Direct);
    }

    #[test]
    fn finds_libgap_in_sibling_lib_dir() {
        let cellar = temp_root("homebrew-sibling-lib");
        let root = cellar.join("libexec");
        let lib = cellar.join("lib");
        write_file(root.join("lib/init.g"));
        write_file(root.join("src/libgap-api.h"));
        write_file(root.join("src/gap_all.h"));
        write_file(root.join("build/config.h"));
        write_file(lib.join("libgap.dylib"));

        let config = discover_gap_config(&DiscoveryEnv {
            root: Some(root.into_os_string()),
            ..DiscoveryEnv::default()
        })
        .unwrap();

        assert_eq!(config.lib_dirs, vec![lib]);
    }

    #[test]
    fn parses_plain_gap_root_output() {
        let root = temp_root("plain-gaproot-output");
        write_file(root.join("lib/init.g"));

        assert_eq!(
            parse_gap_root_stdout(root.to_string_lossy().as_bytes()),
            Some(root)
        );
    }

    #[test]
    fn ignores_banner_output_when_parsing_gap_root() {
        let root = temp_root("banner-gaproot-output");
        write_file(root.join("lib/init.g"));
        let output = format!(
            "Unrecognised command line option: --print-gaproot\n\
             GAP 4.11.1 startup banner\n\
             gap> {}\n",
            root.display()
        );

        assert_eq!(parse_gap_root_stdout(output.as_bytes()), Some(root));
    }

    #[test]
    fn reports_invalid_gap_root() {
        let root = temp_root("invalid-root");
        write_file(root.join("src/libgap-api.h"));
        write_file(root.join("src/gap_all.h"));
        write_file(root.join("libgap.dylib"));

        let err = discover_gap_config(&DiscoveryEnv {
            root: Some(root.into_os_string()),
            ..DiscoveryEnv::default()
        })
        .unwrap_err();

        assert!(err.contains("does not contain `lib/init.g`"));
    }

    fn temp_root(name: &str) -> PathBuf {
        let unique = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        let path = env::temp_dir().join(format!("gap-sys-{name}-{unique}"));
        fs::create_dir_all(&path).unwrap();
        path
    }

    fn write_file(path: PathBuf) {
        fs::create_dir_all(path.parent().unwrap()).unwrap();
        fs::write(path, "").unwrap();
    }
}
